export const TUTOR_FORM_REQUEST = 'TUTOR_FORM_REQUEST'
export const TUTOR_FORM_SUCCESS = 'TUTOR_FORM_SUCCESS'
export const TUTOR_FORM_FAIL = 'TUTOR_FORM_FAIL'

export const TUTOR_DETAILS_REQUEST = 'TUTOR_DETAILS_REQUEST'
export const TUTOR_DETAILS_SUCCESS = 'TUTOR_DETAILS_SUCCESS'
export const TUTOR_DETAILS_FAIL = 'TUTOR_DETAILS_FAIL'
export const TUTOR_DETAILS_RESET = 'TUTOR_DETAILS_RESET'