export const subjects = [
  { value: "Accounting", label: "Accounting" },
  { value: "Art", label: "Art" },
  { value: "Art & Design", label: "Art & Design" },
  { value: "Bangla", label: "Bangla" },
  {
    value: "Bangladesh and Global Studies",
    label: "Bangladesh and Global Studies",
  },
  { value: "Bangladesh Studies", label: "Bangladesh Studies" },
  { value: "Physics", label: "Physics" },
  { value: "Math", label: "Math" },
  { value: "English", label: "English" },
  { value: "Biology", label: "Biology" },
  { value: "Business Entrepreneurship", label: "Business Entrepreneurship" },
  { value: "Business Studies", label: "Business Studies" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Combined Science", label: "Combined Science" },
  { value: "Computer Science", label: "Computer Science" },
  { value: "Economics", label: "Economics" },
  { value: "English Language", label: "English Language" },
  { value: "English Literature", label: "English Literature" },
  { value: "Environment Management", label: "Environment Management" },
  { value: "Ethics and Religions", label: "Ethics and Religions" },
  { value: "Finance and Banking", label: "Finance and Banking" },
  { value: "General Science", label: "General Science" },
  { value: "Higher Math", label: "Higher Math" },
  { value: "History", label: "History" },
  { value: "Law", label: "Law" },
  { value: "Music and Drama", label: "Music and Drama" },
  { value: "Psychology", label: "Psychology" },
  { value: "Religion", label: "Religion" },
  { value: "Science", label: "Science" },
  { value: "Sociology", label: "Sociology" },
  { value: "Statistics", label: "Statistics" },
];
