export const tutorTable = [
  {
    sl: 1,
    curriculum: "National Curriculum (Bangla)",
    bTitle: "ENG123121",
    class: 7,
    subject: "Math",
    totalParticipant: 20,
    vSeat: 2,
    tRating: 4.5,
    dateTime: "20-11-23 4.45 Pm",
    fees: "120BDT/HR",
    action: "action",
  },
  {
    sl: 2,
    curriculum: "National Curriculum (Bangla)",
    bTitle: "ENG123121",
    class: 7,
    subject: "Math",
    totalParticipant: 20,
    vSeat: 2,
    tRating: 4.5,
    dateTime: "20-11-23 4.45 Pm",
    fees: "120BDT/HR",
    action: "action",
  },
  {
    sl: 3,
    curriculum: "National Curriculum (Bangla)",
    bTitle: "ENG123121",
    class: 7,
    subject: "Math",
    totalParticipant: 20,
    vSeat: 2,
    tRating: 4.5,
    dateTime: "20-11-23 4.45 Pm",
    fees: "120BDT/HR",
    action: "action",
  },
  {
    sl: 4,
    curriculum: "National Curriculum (Bangla)",
    bTitle: "ENG123121",
    class: 7,
    subject: "Math",
    totalParticipant: 20,
    vSeat: 2,
    tRating: 4.5,
    dateTime: "20-11-23 4.45 Pm",
    fees: "120BDT/HR",
    action: "action",
  },
];
